export const BACKLOG_QUERY_KEY = ["backlog"] as const;
export const PLAYING_QUERY_KEY = ["backlog_playing"] as const;
export const GAME_STATS_QUERY_KEY = ["game_stats"] as const;

export const PLATFORMS = [
  { value: "PC", label: "PC" },
  { value: "Mac", label: "macOS" },
  { value: "Linux", label: "Linux" },
  { value: "PS1", label: "PlayStation 1" },
  { value: "PS2", label: "PlayStation 2" },
  { value: "PS3", label: "PlayStation 3" },
  { value: "PS4", label: "PlayStation 4" },
  { value: "PS5", label: "PlayStation 5" },
  { value: "PSP", label: "PlayStation Portable" },
  { value: "PSVita", label: "PlayStation Vita" },
  { value: "Xbox", label: "Xbox Classic" },
  { value: "Xbox360", label: "Xbox 360" },
  { value: "XboxOne", label: "Xbox One" },
  { value: "XboxSeries", label: "Xbox Series X/S" },
  { value: "NES", label: "Nintendo Entertainment System (NES)" },
  { value: "SNES", label: "Super Nintendo (SNES)" },
  { value: "N64", label: "Nintendo 64" },
  { value: "GameCube", label: "Nintendo GameCube" },
  { value: "Wii", label: "Nintendo Wii" },
  { value: "WiiU", label: "Nintendo Wii U" },
  { value: "Switch", label: "Nintendo Switch" },
  { value: "GameBoy", label: "Game Boy" },
  { value: "GameBoyColor", label: "Game Boy Color" },
  { value: "GBA", label: "Game Boy Advance" },
  { value: "NDS", label: "Nintendo DS" },
  { value: "3DS", label: "Nintendo 3DS" },
  { value: "SG1000", label: "Sega SG-1000" },
  { value: "MasterSystem", label: "Sega Master System" },
  { value: "Genesis", label: "Sega Genesis / Mega Drive" },
  { value: "SegaCD", label: "Sega CD / Mega-CD" },
  { value: "32X", label: "Sega 32X" },
  { value: "Saturn", label: "Sega Saturn" },
  { value: "Dreamcast", label: "Sega Dreamcast" },
  { value: "GameGear", label: "Sega Game Gear" },
  { value: "Nomad", label: "Sega Nomad" },
  { value: "Atari2600", label: "Atari 2600" },
  { value: "Atari5200", label: "Atari 5200" },
  { value: "Atari7800", label: "Atari 7800" },
  { value: "AtariJaguar", label: "Atari Jaguar" },
  { value: "AtariLynx", label: "Atari Lynx" },
  { value: "3DO", label: "Panasonic 3DO" },
  { value: "CDi", label: "Philips CD-i" },
  { value: "NeoGeo", label: "Neo Geo AES" },
  { value: "NeoGeoCD", label: "Neo Geo CD" },
  { value: "NeoGeoPocket", label: "Neo Geo Pocket" },
  { value: "NeoGeoPocketColor", label: "Neo Geo Pocket Color" },
  { value: "TurboGrafx16", label: "TurboGrafx-16 / PC Engine" },
  { value: "Commodore64", label: "Commodore 64" },
  { value: "Amiga", label: "Amiga" },
  { value: "MSX", label: "MSX" },
  { value: "Oculus", label: "Oculus / Meta Quest VR" },
  { value: "VR", label: "VR (Other)" },
  { value: "Android", label: "Android" },
  { value: "iOS", label: "iOS" },
  { value: "Arcade", label: "Arcade" },
];
