import type { FilterGroup } from "../../../../components/filters/filter-types";

export const FILTER_GROUPS: FilterGroup[] = [
  {
    id: "platforms",
    title: "Plataforma",
    paramKey: "platforms__in",
    type: "multi",
    defaultOpen: true,
    options: [
      { id: "ps5", label: "PS5", value: "167" },
      { id: "ps4", label: "PS4", value: "48" },
      { id: "xbox_series_xs", label: "Xbox Series X|S", value: "169" },
      { id: "xbox_one", label: "Xbox One", value: "49" },
      { id: "switch", label: "Nintendo Switch", value: "130" },
      { id: "switch2", label: "Nintendo Switch 2", value: "508" },
      { id: "windows", label: "Windows", value: "6" },
      { id: "android", label: "Android", value: "34" },
      { id: "ios", label: "iOS", value: "39" },
      { id: "ps3", label: "PS3", value: "9" },
      { id: "xbox_360", label: "Xbox 360", value: "12" },
      { id: "wii_u", label: "Wii U", value: "41" },
      { id: "ps_vita", label: "PlayStation Vita", value: "46" },
      { id: "psp", label: "PlayStation Portable", value: "38" },
      { id: "nintendo_3ds", label: "Nintendo 3DS", value: "37" },
      { id: "nintendo_ds", label: "Nintendo DS", value: "20" },
      { id: "ps2", label: "PS2", value: "8" },
      { id: "ps1", label: "PS1", value: "7" },
      { id: "xbox", label: "Xbox", value: "11" },
      { id: "gamecube", label: "Nintendo GameCube", value: "21" },
      { id: "snes", label: "Super Nintendo (SNES)", value: "19" },
      { id: "nes", label: "Nintendo (NES)", value: "18" },
      { id: "mega_drive_genesis", label: "Sega Mega Drive/Genesis", value: "29" },
      { id: "master_system", label: "Sega Master System", value: "64" },
      { id: "saturn", label: "Sega Saturn", value: "32" },
      { id: "dreamcast", label: "Dreamcast", value: "23" },
      { id: "gba", label: "Game Boy Advance", value: "24" },
      { id: "gbc", label: "Game Boy Color", value: "22" },
      { id: "gb", label: "Game Boy", value: "33" },
      { id: "super_famicom", label: "Super Famicom", value: "58" },
      { id: "steamos", label: "SteamOS", value: "92" },
      { id: "steamvr", label: "SteamVR", value: "163" },
      { id: "atari_2600", label: "Atari 2600", value: "59" },
      { id: "atari_7800", label: "Atari 7800", value: "60" },
      { id: "neogeo_mvs", label: "Neo Geo MVS", value: "79" },
    ],
  },
  {
    id: "release-date",
    title: "Data",
    paramKey: "first_release_date",
    type: "range",
    defaultOpen: false,
    options: [],
    range: {
      mode: "date",
      fromParam: "first_release_date_from",
      toParam: "first_release_date_to",
      min: 0,
      max: 9999999999,
      step: 1,
      fromPlaceholder: "",
      toPlaceholder: "",
    },
  },
];
